#include "CppUnitTest.h"

#include <Windows.h>

#include <chrono>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <thread>
#include <vector>

/*
Purpose:
This file contains integration and system-level MSTest tests for the full
distributed aircraft-ground communication workflow.

Importance of this file:
These tests verify that the client and server work together correctly as an
operational pair, not just as isolated units. They validate runtime behavior,
generated artifacts, logging, end-to-end completion, and transfer sequencing.

Testing focus in this file:
- full end-to-end session completion
- runtime log generation
- large transfer file generation
- command and status exchange visibility in logs
- disconnect sequence visibility in logs
- runtime artifact generation in the output directory
- large-transfer marker ordering

DAL-oriented commentary:
- DAL A relevance:
  Full-path validation of distributed communication helps support confidence that
  critical flows reject invalid states and complete expected safe transitions.
- DAL B relevance:
  End-to-end client/server exchanges, command flow, and transfer sequencing are
  operationally major behaviors with potentially serious impact if wrong.
- DAL C relevance:
  Logging, artifact verification, and transfer ordering strongly support reliable
  diagnostics, auditability, and operational correctness.
- DAL D relevance:
  Some artifact-location checks are support-oriented rather than primary control,
  but still important for test evidence and traceability.
- DAL E relevance:
  Cosmetic-only behavior is not the focus here; these are functional runtime tests.
*/

using namespace Microsoft::VisualStudio::CppUnitTestFramework;
namespace fs = std::filesystem;

namespace AGCIntegrationSystemTests
{
    namespace
    {
        /*
        Helper: findRepoRoot
        Purpose:
        Walk upward from the current path until the project root is found.

        Why needed:
        Integration tests must reliably locate the real project repository
        structure regardless of where the test host is launched from.

        DAL commentary:
        This helper is supportive rather than directly safety-critical.
        Closest relevance: DAL D
        */
        fs::path findRepoRoot()
        {
            fs::path current = fs::current_path();

            for (int depth = 0; depth < 8; ++depth)
            {
                if (fs::exists(current / "include" / "common.hpp"))
                {
                    return current;
                }

                if (current.has_parent_path() == false)
                {
                    break;
                }

                current = current.parent_path();
            }

            Assert::Fail(L"Could not locate repository root.");
            return fs::current_path();
        }

        /*
        Helper: findBuiltExecutable
        Purpose:
        Search known output directories for the requested built executable.

        Why needed:
        Integration/system tests must launch the actual product executables
        generated by the build process.

        DAL commentary:
        This supports system-test execution but is not itself a critical runtime
        control of the product.
        Closest relevance: DAL D
        */
        fs::path findBuiltExecutable(const fs::path& repoRoot, const std::wstring& exeName)
        {
            const std::vector<fs::path> candidates =
            {
                repoRoot / "build" / "Debug" / exeName,
                repoRoot / "build" / exeName,
                repoRoot / "build" / "Release" / exeName
            };

            for (const auto& path : candidates)
            {
                if (fs::exists(path))
                {
                    return path;
                }
            }

            Assert::Fail((L"Executable not found: " + exeName).c_str());
            return fs::path{};
        }

        /*
        Helper: startProcess
        Purpose:
        Launch an executable for integration/system test execution.

        Why needed:
        These tests validate the real distributed runtime path by starting the
        actual server and client executables.

        DAL commentary:
        End-to-end launch of the product is conceptually closer to DAL B / C
        relevance because it exercises major operational behavior across both
        applications.
        */
        PROCESS_INFORMATION startProcess(const fs::path& exePath)
        {
            STARTUPINFOW startupInfo{};
            startupInfo.cb = sizeof(startupInfo);

            PROCESS_INFORMATION processInfo{};
            std::wstring commandLine = L"\"" + exePath.wstring() + L"\"";
            std::vector<wchar_t> buffer(commandLine.begin(), commandLine.end());
            buffer.push_back(L'\0');

            const BOOL ok = CreateProcessW(
                nullptr,
                buffer.data(),
                nullptr,
                nullptr,
                FALSE,
                0U,
                nullptr,
                exePath.parent_path().wstring().c_str(),
                &startupInfo,
                &processInfo);

            if (ok == FALSE)
            {
                Assert::Fail((L"Failed to start process: " + exePath.wstring()).c_str());
            }

            return processInfo;
        }

        /*
        Helper: waitForProcess
        Purpose:
        Wait for the launched process to complete or terminate it on timeout.

        Why needed:
        Prevents integration/system tests from hanging indefinitely.

        DAL commentary:
        Timeout handling supports controlled and bounded test execution.
        Closest relevance: DAL C / D in the context of test robustness.
        */
        DWORD waitForProcess(PROCESS_INFORMATION& processInfo, DWORD timeoutMs)
        {
            const DWORD waitResult = WaitForSingleObject(processInfo.hProcess, timeoutMs);

            if (waitResult != WAIT_OBJECT_0)
            {
                TerminateProcess(processInfo.hProcess, 1U);
                Assert::Fail(L"Process timed out.");
            }

            DWORD exitCode = 1U;
            GetExitCodeProcess(processInfo.hProcess, &exitCode);

            CloseHandle(processInfo.hThread);
            CloseHandle(processInfo.hProcess);

            return exitCode;
        }

        /*
        Helper: readAllText
        Purpose:
        Read a full text file into a std::string for content inspection.

        Why needed:
        Used for checking runtime log content and log-event ordering.

        DAL commentary:
        This is evidence-oriented support logic.
        Closest relevance: DAL D
        */
        std::string readAllText(const fs::path& path)
        {
            std::ifstream input(path);
            std::ostringstream buffer{};
            buffer << input.rdbuf();
            return buffer.str();
        }

        /*
        Helper: deleteIfExists
        Purpose:
        Remove old runtime artifacts before a new end-to-end scenario.

        Why needed:
        Ensures tests are independent and do not pass because of leftover files
        from prior runs.

        DAL commentary:
        Test independence is important for trustworthy evidence.
        Closest relevance: DAL C / D
        */
        void deleteIfExists(const fs::path& path)
        {
            if (fs::exists(path))
            {
                fs::remove(path);
            }
        }

        /*
        Struct: EndToEndRunResult
        Purpose:
        Captures the essential outputs of a full runtime scenario.

        Why needed:
        Multiple tests reuse the result of a launched client/server session.

        DAL commentary:
        This is a simple support container; lowest direct criticality in this file.
        Closest relevance: DAL D / E
        */
        struct EndToEndRunResult
        {
            fs::path outputDirectory;
            DWORD clientExitCode;
            DWORD serverExitCode;
        };

        /*
        Helper: runEndToEndScenario
        Purpose:
        Launch the server, then the client, wait for both to finish, and return
        runtime output information.

        Why needed:
        This is the core reusable scenario for most integration/system tests.

        DAL commentary:
        This helper exercises the entire major communication path of the project:
        connection verification, telemetry, command exchange, status request,
        large transfer, and disconnect.

        Closest conceptual relevance:
        DAL B / C
        because it validates major distributed behavior across both endpoints.
        */
        EndToEndRunResult runEndToEndScenario()
        {
            const fs::path repoRoot = findRepoRoot();
            const fs::path serverExe = findBuiltExecutable(repoRoot, L"server.exe");
            const fs::path clientExe = findBuiltExecutable(repoRoot, L"client.exe");

            const fs::path outputDirectory = serverExe.parent_path();

            // Clean previous artifacts so the scenario is independent.
            deleteIfExists(outputDirectory / "server_log.csv");
            deleteIfExists(outputDirectory / "client_log.csv");
            deleteIfExists(outputDirectory / "received_diagnostic_payload.bin");

            PROCESS_INFORMATION serverProcess = startProcess(serverExe);

            // Allow the server enough time to reach the listening state.
            std::this_thread::sleep_for(std::chrono::milliseconds(1500));

            PROCESS_INFORMATION clientProcess = startProcess(clientExe);

            const DWORD clientExit = waitForProcess(clientProcess, 60000U);
            const DWORD serverExit = waitForProcess(serverProcess, 60000U);

            EndToEndRunResult result{};
            result.outputDirectory = outputDirectory;
            result.clientExitCode = clientExit;
            result.serverExitCode = serverExit;
            return result;
        }
    }

    TEST_CLASS(IntegrationSystemTests)
    {
    public:
        TEST_METHOD(EndToEnd_ClientAndServerCompleteSuccessfully)
        {
            /*
            DAL commentary:
            This is a high-value system-level regression test. It confirms the
            entire client/server session can complete successfully with zero exit
            codes on both ends.

            Closest relevance:
            DAL B / C
            because it validates the main operational path of the project.
            */
            const EndToEndRunResult result = runEndToEndScenario();

            Assert::AreEqual(static_cast<DWORD>(0U), result.clientExitCode);
            Assert::AreEqual(static_cast<DWORD>(0U), result.serverExitCode);
        }

        TEST_METHOD(Integration_LogsAreGeneratedAndContainExpectedEvents)
        {
            /*
            DAL commentary:
            Logging is explicitly required by the project and is critical for
            traceability, debugging, and audit evidence.

            Why important:
            In a safety/reliability context, the existence and content of runtime
            logs helps explain what the distributed system actually did.

            Closest relevance:
            DAL C
            because logging strongly supports operational assurance and evidence.
            */
            const EndToEndRunResult result = runEndToEndScenario();

            Assert::AreEqual(static_cast<DWORD>(0U), result.clientExitCode);
            Assert::AreEqual(static_cast<DWORD>(0U), result.serverExitCode);

            const fs::path clientLog = result.outputDirectory / "client_log.csv";
            const fs::path serverLog = result.outputDirectory / "server_log.csv";

            Assert::IsTrue(fs::exists(clientLog), L"client_log.csv was not generated.");
            Assert::IsTrue(fs::exists(serverLog), L"server_log.csv was not generated.");

            const std::string clientText = readAllText(clientLog);
            const std::string serverText = readAllText(serverLog);

            Assert::IsTrue(clientText.find("CONNECT_ACK") != std::string::npos);
            Assert::IsTrue(clientText.find("TELEMETRY_ACK") != std::string::npos);
            Assert::IsTrue(serverText.find("CONNECT_REQUEST") != std::string::npos);
            Assert::IsTrue(serverText.find("LARGE_DATA_START") != std::string::npos);
            Assert::IsTrue(serverText.find("LARGE_DATA_END") != std::string::npos);
        }

        TEST_METHOD(System_LargeTransferProducesReceivedFileAboveOneMegabyte)
        {
            /*
            DAL commentary:
            This validates one of the most important explicit system requirements:
            a large object transfer of at least 1 MB from server to client.

            Closest relevance:
            DAL B / C
            because this is a major end-to-end feature with transfer integrity
            and artifact creation implications.
            */
            const EndToEndRunResult result = runEndToEndScenario();

            Assert::AreEqual(static_cast<DWORD>(0U), result.clientExitCode);
            Assert::AreEqual(static_cast<DWORD>(0U), result.serverExitCode);

            const fs::path receivedFile =
                result.outputDirectory / "received_diagnostic_payload.bin";

            Assert::IsTrue(fs::exists(receivedFile), L"Received file was not created.");

            const auto fileSize = fs::file_size(receivedFile);
            Assert::IsTrue(fileSize >= 1049600ULL,
                L"Received file is smaller than required.");
        }

        TEST_METHOD(Integration_CommandAndStatusExchangeArePresentInLogs)
        {
            /*
            DAL commentary:
            Command dispatch and status-response behavior represent important
            operational exchange paths between server and client.

            Closest relevance:
            DAL B / C
            because incorrect command/status sequencing could undermine intended
            control flow and monitoring.
            */
            const EndToEndRunResult result = runEndToEndScenario();

            Assert::AreEqual(static_cast<DWORD>(0U), result.clientExitCode);
            Assert::AreEqual(static_cast<DWORD>(0U), result.serverExitCode);

            const fs::path clientLog = result.outputDirectory / "client_log.csv";
            const fs::path serverLog = result.outputDirectory / "server_log.csv";

            Assert::IsTrue(fs::exists(clientLog), L"client_log.csv was not generated.");
            Assert::IsTrue(fs::exists(serverLog), L"server_log.csv was not generated.");

            const std::string clientText = readAllText(clientLog);
            const std::string serverText = readAllText(serverLog);

            Assert::IsTrue(clientText.find("COMMAND") != std::string::npos);
            Assert::IsTrue(clientText.find("COMMAND_ACK") != std::string::npos);
            Assert::IsTrue(clientText.find("STATUS_RESPONSE") != std::string::npos);

            Assert::IsTrue(serverText.find("COMMAND") != std::string::npos);
            Assert::IsTrue(serverText.find("COMMAND_ACK") != std::string::npos);
            Assert::IsTrue(serverText.find("DATA_REQUEST") != std::string::npos);
            Assert::IsTrue(serverText.find("STATUS_RESPONSE") != std::string::npos);
        }

        TEST_METHOD(Integration_DisconnectSequenceIsLogged)
        {
            /*
            DAL commentary:
            Controlled disconnect behavior is important because safe session
            termination is part of predictable system operation.

            Closest relevance:
            DAL C
            because clean shutdown and traceability reduce ambiguity during
            operational analysis.
            */
            const EndToEndRunResult result = runEndToEndScenario();

            Assert::AreEqual(static_cast<DWORD>(0U), result.clientExitCode);
            Assert::AreEqual(static_cast<DWORD>(0U), result.serverExitCode);

            const fs::path clientLog = result.outputDirectory / "client_log.csv";
            const fs::path serverLog = result.outputDirectory / "server_log.csv";

            Assert::IsTrue(fs::exists(clientLog), L"client_log.csv was not generated.");
            Assert::IsTrue(fs::exists(serverLog), L"server_log.csv was not generated.");

            const std::string clientText = readAllText(clientLog);
            const std::string serverText = readAllText(serverLog);

            Assert::IsTrue(clientText.find("DISCONNECT") != std::string::npos);
            Assert::IsTrue(serverText.find("DISCONNECT") != std::string::npos);
        }

        TEST_METHOD(System_RuntimeArtifactsAreCreatedInOutputDirectory)
        {
            /*
            DAL commentary:
            Runtime artifact creation is important for traceability and evidence.
            This is less critical than the communication itself, but still very
            important for proving system behavior and debugging problems.

            Closest relevance:
            DAL C / D
            due to evidence and post-run analysis value.
            */
            const EndToEndRunResult result = runEndToEndScenario();

            Assert::AreEqual(static_cast<DWORD>(0U), result.clientExitCode);
            Assert::AreEqual(static_cast<DWORD>(0U), result.serverExitCode);

            Assert::IsTrue(fs::exists(result.outputDirectory / "client_log.csv"),
                L"client_log.csv missing from runtime directory.");

            Assert::IsTrue(fs::exists(result.outputDirectory / "server_log.csv"),
                L"server_log.csv missing from runtime directory.");

            Assert::IsTrue(fs::exists(result.outputDirectory / "received_diagnostic_payload.bin"),
                L"received_diagnostic_payload.bin missing from runtime directory.");
        }

        TEST_METHOD(System_LargeTransferMarkersAppearInCorrectOrder)
        {
            /*
            DAL commentary:
            Sequencing of large-transfer events is important because it shows the
            server follows the intended structured communication flow.

            Closest relevance:
            DAL C
            because correct order supports reliable interpretation and debugging.
            */
            const EndToEndRunResult result = runEndToEndScenario();

            Assert::AreEqual(static_cast<DWORD>(0U), result.clientExitCode);
            Assert::AreEqual(static_cast<DWORD>(0U), result.serverExitCode);

            const fs::path serverLog = result.outputDirectory / "server_log.csv";
            Assert::IsTrue(fs::exists(serverLog), L"server_log.csv was not generated.");

            const std::string serverText = readAllText(serverLog);

            const std::size_t startPos = serverText.find("LARGE_DATA_START");
            const std::size_t endPos = serverText.find("LARGE_DATA_END");

            Assert::IsTrue(startPos != std::string::npos, L"LARGE_DATA_START not found.");
            Assert::IsTrue(endPos != std::string::npos, L"LARGE_DATA_END not found.");
            Assert::IsTrue(startPos < endPos, L"LARGE_DATA_START should appear before LARGE_DATA_END.");
        }
    };
}